### ISSUE TITLE
Move webapps into new AWS region / VPC

### ISSUE THREAD

**Issue by mattandrews** [biglotteryfund/blf-alpha#1195]
# TODO:
- [x] Configure `appspec.yml`/`bootstrap.js` to determine correct `APP_ENV`
- [x] Copy WWW secrets to eu-west-2
- [x] Make WWW app get its secrets from `eu-west-2`
- [x] Recreate Cloudwatch monitoring / ASG policies
- [x] Create PROD instances of CMS + WWW apps
- [x] Point Cloudfront / DNS at new instances for CMS + WWW (after syncing CMS database)

# Blocked until DNS change is done:
- [x] Update Travis to deploy to new EB/Codedeploy groups
- [x] Update Lambda notifier to get data from new groups
- [x] Update dashboard app to fetch data from new groups
- [x] Delete EC2 instances / ELBs / Elastic Beanstalk / CodeDeploy apps
- ~Delete now-unused public database~
- ~Rename session from `blf-alpha-session` to something without `alpha` in it.~
- ~Point WWW app at VPC DB (means updating secrets, so must happen post-deploy)~

# Post-cleanup tasks
- [x] Move Cloudwatch alerts (mail/timings) to `eu-west-2`?
- [x] Recreate Cloudwatch dashboard in VPC env
- ~Remove `blf-travis-test` S3 bucket~ Extracted out into new ticket
- ~Move SES to `eu-west-2`?~ not available in `eu-west-2`

**Comment by davidrapson** [comment]
Extracted database tasks into https://github.com/biglotteryfund/blf-alpha/issues/1207 as we're going to do this one building connections fund closes.
