### ISSUE TITLE
Build EYP prototype

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#134]
This includes:
 - [x] PDDs for four tabs of content, signed off (#137)
 - [x] Wireframes showing structure signed off (#135)
 - [ ] Creative signed off (#136)
 - [x] Imagery sourced (#138)

**Comment by ChloeAlper** [comment]
Prototype 1 link: https://invis.io/AZD2H8KHX

**Comment by ChloeAlper** [comment]
Prototype with original copy: https://invis.io/T3D2IR0U5
