### ISSUE TITLE
Make various improvements to the style guide

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#169]
- [x] Update all new style pages to reflect new nav/header/hero images #202
- [ ] Implement new grid layout onto all existing pages #156
- [ ] Add a colours section #391
- [ ] Add link styles #392
- [ ] Tidy up font list #389
- [ ] Fix line lengths #164 
- [x] Add all existing components #390

**Comment by mattandrews** [comment]
Closing due to lack of movement – think most of these issues have been superseded by now so we can re-open tickets where needed. Pruning FTW!
