### ISSUE TITLE
Make various hero image and nav improvements on Homepage and 10k pages

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#197]
- [x] Update the under 10k hero image to show an appropriate value project, and reinstate the caption
- [x] Create a medium sized image crop for better tablet experience (#234)
- [x] Implement hero image rotation upon user re-visiting homepage (#234)
- [x] Tidy and reduce height of overlaid text on hero images on home page (#240)
- [x] Implement optimisations to iPad / inbetween breakpoints (#240)

**Comment by davidrapson** [comment]
hero rotation here: https://github.com/biglotteryfund/blf-alpha/pull/234

**Comment by davidrapson** [comment]
Spacing and layout improvements here: https://github.com/biglotteryfund/blf-alpha/pull/240

**Comment by stevekeene** [comment]
Looks good - very happy with these!

**Comment by ChloeAlper** [comment]
@davidrapson @mattandrews the new 10k heroes are ready to go. Mobile, iPad and desktop crops can be found here:

Dropbox (Big Lottery Fund)/Big Lottery Fund Team Folder/Digital Creative/Page 28 - Home/Assets/under-10k-hero-mobile.jpg

Please hide the caption on the under 10k for now as I am awaiting grant amount confirmation. The caption for above 10k is "Passion4Fusion, Grant £36,700"

**Comment by davidrapson** [comment]
10k images have been updated as part of https://github.com/biglotteryfund/blf-alpha/pull/251 , I've left the caption off the under 10k page until we have one.

**Comment by davidrapson** [comment]
All the changes listed here are now live.

**Comment by ChloeAlper** [comment]
@davidrapson @mattandrews I have the grant amount information for the under 10k hero so we can un-hide that caption when you have a mo:

"Friends of Greenwich Peninsula Ecology Park, Grant £5,350*"

**Comment by davidrapson** [comment]
@ChloeAlper Does the * mean that we need the caveat to the footer?

**Comment by mattandrews** [comment]
Have removed it!

**Comment by ChloeAlper** [comment]
@stevekeene @TomSteinberg please see suggested new home page hero image following diversity  conversation with Engagement today. Please note that this image is no longer being used on the below 10k page. I think this image is strong so I am glad to have (I hope) found a home for it.

![home-20171011](https://user-images.githubusercontent.com/27225981/31452202-27321c92-aea6-11e7-82ad-e089e7aeb45b.png)

**Comment by TomSteinberg** [comment]
Good image, go for it.

**Comment by mattandrews** [comment]
@ChloeAlper when you're back, if you can supply the three images for this we'll get it live!

**Comment by ChloeAlper** [comment]
@davidrapson the new Somewhereto hero images for mobile, desktop, ipad are copying across to the Dropbox, all suffixed with a 4. For example: Dropbox (Big Lottery Fund)/Big Lottery Fund Team Folder/Digital Creative/Page 28 - Home/Assets/home-hero-4.jpg 

Image caption: 'Somewhereto, Grant 7M'
