### ISSUE TITLE
Configure Sentry to track application errors and Content-Security-Policy violations

### ISSUE THREAD

**Issue by davidrapson** [biglotteryfund/blf-alpha#237]
After discussion with @mattandrews I've signed up for the free tier of [Sentry](https://sentry.io/) to help us better track errors on the new website. There are few parts to this which can happen separately.

**Server-side error tracking**

- [x] Clear out unused Twitter keys from parameter store (#255)
- [x] Update `get_secrets` script to avoid needing to name parameters, fetch all (#255)
- [x] Store private-DSN in EC2 parameter store (#255)
- [x] Configure Raven (Sentry client) with private-DSN (#256)
- [x] Configure global request and error handlers (#256)
- [x] Throw a test error and confirm it is reported (#256)

**Client-side error tracking**

- [x] Configure client-side code with public-DSN (#257)
- [x] Configure common filters in sentry admin (#257)
- [x] Throw a test error and confirm it is reported (#257)

**Configure Content-Security-Policy tracking**

- [x] Generate CSP report URL within Sentry (#258)
- [x] Configure CSP `report-uri` to point to Sentry URL (#258)
- [x] Confirm CSP warnings are reported

**Sentry Workflow Improvements**

- [x] Configure Slack notifications from new error reports
- [x] Mark environments in sentry reports

**Comment by mattandrews** [comment]
Info on fetching existing params: http://docs.aws.amazon.com/cli/latest/reference/ssm/get-parameter-history.html

**Comment by davidrapson** [comment]
Marking this as closed as all of the initial set up has happened. We can review this further once we've had a week or so of error reports in to see what things need improving.
