### ISSUE TITLE
Make improvements to free material order form

### ISSUE THREAD

**Issue by mattandrews** [biglotteryfund/blf-alpha#384]
- [ ] Send emails in JSON format (https://github.com/biglotteryfund/blf-alpha/issues/380)
- [x] Reduce number of fields: https://github.com/biglotteryfund/blf-alpha/issues/62
- [x] Make copy changes: https://github.com/biglotteryfund/blf-alpha/issues/382
- [x] Email customers after orders: https://github.com/biglotteryfund/blf-alpha/issues/381
- [x] Clarify ordering limits on plaques: https://github.com/biglotteryfund/blf-alpha/issues/107
- [x] Store metadata on orders: https://github.com/biglotteryfund/blf-alpha/issues/386
